services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pravoles
    ports:
      - "5432:5432"
    volumes:
      - pravoles_pg:/var/lib/postgresql/data

volumes:
  pravoles_pg:
